name: Trigger Netlify deploy via hook

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Call Netlify build hook
        run: curl -s -X POST -d '{}' "${{ secrets.NETLIFY_BUILD_HOOK }}"